### ISSUE TITLE
Memory section only updates on page refresh.

### ISSUE THREAD

**Issue by SalvorinFex** [NeonHorizon/berryio#20]
I have been running this on a couple of Pis and it happens on all of them.
After running Berryio for a while, I have to refresh the page to get updated Memory data.

**Comment by myxingchao** [comment]
I tried what you wrote berryio, but I open the browser midfielder seeking landing, the account password I do not know, tell me cry, and look forward to your reply, thank you

**Comment by NeonHorizon** [comment]
The password is the same as your Raspberry Pi login, which means if you haven't changed it its pi for the username and raspberry for the password.

**Comment by myxingchao** [comment]
Mr. Bull, your berryio really good, and now I want to improve my build a platform, you can share the LCD1602 diagram berryio

**Comment by myxingchao** [comment]
Mr.Bull,your berryio are pretty good!Could you please share the  LCD1602 circuit diagram  to me .much more shanks.Because of translation problems, just could not clearly express, I am deeply sorry

**Comment by SalvorinFex** [comment]
This can be closed now, I don't know why this other user is using this for another topic.
