### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by shipmodeller** [NeonHorizon/berryio#21]
I need to rip down a raspberry pi and remove Berryio without having to do a clean install.  The usual

sudo apt-get uninstall berryio

obviously doesn't work, and Debian and I aren't that familiar to be able to figure out the uninstall process.  I like having the pi's email me on wakeup, but I have some conflicts to resolve, so would like to have an uninstall process.  thanks

**Comment by NeonHorizon** [comment]
Normally I would recommend simply re-imaging your Pi or reverting to a backup image but if none of those options are available you can do the following which will get rid of BerryIO. I've not tested these commands personally but they should be fine.

sudo a2dissite berryio
sudo a2ensite default
sudo service apache2 restart
sudo rm /etc/apache2/sites-available/berryio

sudo rm /etc/network/if-up.d/berryio_email_ip

sudo rm /etc/php5/conf.d/msmtp.ini
sudo rm /etc/msmtprc

sudo rm /etc/sudoers.d/berryio
sudo rm /usr/bin/berryio

sudo rm -fr /usr/share/berryio
sudo rm -fr /var/log/berryio
sudo rm -fr /etc/berryio

Once you have done that BerryIO will be removed but you may be left with some of the applications it installs to use. You should only uninstall these if you are sure you are not using them for other programs. php5 is programming language like Python, apache2 is a webserver and msmtp sends emails.

sudo apt-get remove php5
sudo apt-get remove apache2
sudo apt-get remove msmtp

**Comment by shipmodeller** [comment]
Thank you .. that seemed to clear it up./..  I'll put that in a bash *.sh script for future use.  Thanks again.
Love Berryio... does a good job
