### ISSUE TITLE
Why no php opening tags on any php files?

### ISSUE THREAD

**Issue by allen00se** [NeonHorizon/berryio#23]
When i run "berryio" it just prints the file on the terminal... i examine the file and it looks to be a php file with no <?php tag at the beggining... only <?

My understanding of php is that if there is no <?php tag it will interpret at html and thus just print the file. I examined more of the .php files and non of them have the opening tag. Please explain, im sure I am missing something.

**Comment by NeonHorizon** [comment]
The install script should have installed the following file: https://github.com/NeonHorizon/berryio/blob/master/default_config/php5/cli/conf.d/berryio.ini

This allows <? to be used instead of <?php

If you ran the install script it may be that you have an old version of Raspbian that doesn't use the conf.d type of configuration for PHP.

**Comment by allen00se** [comment]
Brand new Raspbian install as of last night and freshly updated as well.

**Comment by allen00se** [comment]
Also there are some syntax changes you will need for the apache configuration if you want it to be compatible with the latest Raspbian...I had to change to these lines in the installer

a2dissite 000-default.conf || { echo -e "Install failed!" 1>&2; exit 1; }
a2ensite berryio.conf || { echo -e "Install failed!" 1>&2; exit 1; }

and I had to remove "Options Indexes None" and "Options FollowSymLinks" from the apache conf file in order to get apache to start.

**Comment by NeonHorizon** [comment]
Interesting, did you do a clean install of the latest version of BerryIO as "Options Indexes None" was removed in this commit on the 10th October?
https://github.com/NeonHorizon/berryio/commit/f6facc8145e61985dbb31a89de47f9ef393b779f

**Comment by allen00se** [comment]
well, actually I was working off of a fork... I just updated to your master and now everthing works. Sorry for the hassle.

**Comment by NeonHorizon** [comment]
LOL, thats a relief, I thought I was in for a few days work there :)
