### ISSUE TITLE
Web GPIO Status interface doesn't respond

### ISSUE THREAD

**Issue by muppet666** [NeonHorizon/berryio#24]
Hi,
after installing Berryio on RPI B and 2B  (Jessie, with kernel 4.1.13 from November 2015) 
GPIO access via web interface works fine. Second Step, applying camera_setup.
Camera works fine but GPIO Access via Web is no longer possible. No reaction, no change on 
web site.

With user pi on console I can modify gpio ports with berryio commands.

Seems to be a grant problem for www-data after doing "sudo berryio camera_setup". 
www-data is still member of gpio. 

Every time I re-run installing berryio and camera-setup, same result.

Any idea?

Thanks
Ludger

**Comment by NeonHorizon** [comment]
Hi Ludger,
I'll check into this and get back to you.

**Comment by muppet666** [comment]
Wonderful, issue is fixed. Thank you very much!!
Berryio is cool.
