### ISSUE TITLE
No momentary-on (pulse output) support for GPIO output pins.

### ISSUE THREAD

**Issue by TravisJBennett** [NeonHorizon/berryio#26]
I'm trying to add momentary-on (pulse output) support for GPIO pins. 
This is to replace a function that was available in WebIOPi. 
I use to to momentarily close a relay that simulates pressing a button. One click should send a momentary pulse.

So, I'm trying to tweak the images and code.  I want to change the GPIO mode switches to be four-way switches instead of three-way switches, to include a momentary-out option.
Anybody have the source (Photoshop/Gimp?) images for those in usr\share\berryio\www\images\gpio\mode ?
![out](https://cloud.githubusercontent.com/assets/6711962/25067277/3ffdf36c-220c-11e7-8cbe-6f5e81074f65.png)

Or, is there a better way to do this?

**Comment by NeonHorizon** [comment]
If I remember correctly I made them in Paint Shop Pro from real control panel photos, unfortunately I don't have Paint Shop Pro any more as I stopped using Windows. That particular image you could just rotate the centre part to vertical and add a different option. Matching the font would be tricky but you could just replace with your own similar font.

**Comment by TravisJBennett** [comment]
Despite being able to modify the graphics, I dropped this idea and software package in favor of a fork of a software I used before.
