### ISSUE TITLE
Working on php 7.0 and Ubuntu Mate 16.04!

### ISSUE THREAD

**Issue by mibofra** [NeonHorizon/berryio#27]
It` seems to be working with php7.0 and Ubuntu Mate 16.04(.02 in my case). Just had to change the paths and the names of the packages into the install script. (Sorry, the code tag isn't working with this ahah) [EDIT] I've fixed the Markdown :)

```echo -e "\nInstalling the prerequisites...."
apt-get -y install ethtool wireless-tools msmtp apache2 php libapache2-mod-php pwauth git || { echo -e "Install failed!" 1>&2; exit 1; }

echo -e "\nRemoving any old copies of BerryIO...."
rm -fr /usr/share/berryio || { echo -e "Install failed!" 1>&2; exit 1; }

echo -e "\nRetrieving latest copy of BerryIO from GitHub...."
git clone https://github.com/NeonHorizon/berryio.git /usr/share/berryio/

echo -e "\nCopying in the default config...."
cp -R /usr/share/berryio/default_config/berryio /etc || { echo -e "Install failed!" 1>&2; exit 1; }
cp -R /usr/share/berryio/default_config/apache2 /etc || { echo -e "Install failed!" 1>&2; exit 1; }
cp /usr/share/berryio/default_config/php5/apache2/conf.d/* /etc/php/7.0/apache2/conf.d || { echo -e "Install failed!" 1>&2; exit 1; }
cp /usr/share/berryio/default_config/php5/cli/conf.d/* /etc/php/7.0/cli/conf.d || { echo -e "Install failed!" 1>&2; exit 1; }
```

I think you can simply adapt the script, put a switch to know on wich OS you are installing it, and it will work fine as expected. Anyway this could be a "wishlist" label.

**Comment by NeonHorizon** [comment]
Since you already did the work I might give it ago :)
I'm guessing this was on a Pi3?

**Comment by mibofra** [comment]
Yes, it was on a Raspberry PI 3

**Comment by NeonHorizon** [comment]
I just had to make a bunch of changes for Raspbian Stretch. The ones you mentioned above were included.
Can you give the current version 2.0 a go and let me know if it works?

**Comment by mibofra** [comment]
I'm trying my new build of Parrot Sec OS on the rpi3. There is php7 also on that image. So, just the time to verify this image, and I'll test berryio directly on it.

**Comment by mibofra** [comment]
Hi! Sorry but just I'm pretty busy man. Anyway, it's still working on the recent versions of ubuntu too

**Comment by NeonHorizon** [comment]
Thanks...
