### ISSUE TITLE
berryio

### ISSUE THREAD

**Issue by prometheus3995** [NeonHorizon/berryio#29]
i am trying to install berryio on my pi3. have done sudo apt-get update and sudo apt-get upgrade, installed apache2, but when i try and run the berryio_install.sh as per the installation instructions in the INSTALL.README.txt
I get the following output in terminal.

> pi@TankPi:~ $ chmod +x berryio_install.sh
pi@TankPi:~ $ sudo ./berryio_install.sh

BerryIO Installer
-----------------

Installing the prerequisites....
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libapache2-mod-php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5' has no installation candidate
E: Package 'libapache2-mod-php5' has no installation candidate
Install failed!

Can i get some help please

**Comment by NeonHorizon** [comment]
I have now got BerryIO working properly on Stretch.
Its not had much testing yet but appears to work, let me know if you have any issues :)
