### ISSUE TITLE
Not working on Buster

### ISSUE THREAD

**Issue by JVTEAM** [NeonHorizon/berryio#32]
After several good installs on stretch, I'm finding the Rpi4 doesn't want to work.

**Comment by NeonHorizon** [comment]
Whats the issue?

**Comment by JVTEAM** [comment]
It's not generating the webpage that the stretch rpi's get.  

Run berryio help and you get this instead:

<?
/*------------------------------------------------------------------------------
 BerryIO Command Line Bootstrap
------------------------------------------------------------------------------*/
$EXEC_MODE = 'cli';
require_once('/etc/berryio/paths.php');
require_once(BASE.'/includes/configs/paths.php');


/*------------------------------------------------------------------------------
  Load the commonly used config, settings and functions
------------------------------------------------------------------------------*/
require_once(CONFIGS.'common.php');
require_once(SETTINGS.'common.php');
require_once(FUNCTIONS.'common.php');


/*------------------------------------------------------------------------------
  Check theres a requested controller and load it checking for root if required
------------------------------------------------------------------------------*/
$args = $argv;
$EXEC = basename(array_shift($args));

// Show the help command by default
if(count($args) < 1)
  $args[0] = 'help';

// Check for commands which need to be run as root
if(posix_getuid() != 0 && in_array($args[0], $GLOBALS['NEED_SUDO']))
{
  $page['content'] = message('ERROR: '.$EXEC.' '.$args[0].' must be run as root'.PHP_EOL.'Try: sudo '.$EXEC.' '.implode(' ', $args));
  $GLOBALS['SUCCESS'] = FALSE;
}
else
{
  // Presume its OK unless stated otherwise
  $GLOBALS['SUCCESS'] = TRUE;

  // Run command
  $page['content'] = call_user_func_array('command', $args);
}

/*------------------------------------------------------------------------------
  Output the page
------------------------------------------------------------------------------*/
echo view('layout/common', $page);

exit(!$GLOBALS['SUCCESS'] + 0);

**Comment by NeonHorizon** [comment]
It looks like your install is corrupted.
Can you try running the installer again?

**Comment by JVTEAM** [comment]
No impact after running it again

**Comment by NeonHorizon** [comment]
I think I know what this is...
What do you get if you run php --version

**Comment by JVTEAM** [comment]
PHP 7.3.4-2 (cli) (built: Apr 13 2019 19:05:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4-2, Copyright (c) 1999-2018, by Zend Technologies

**Comment by NeonHorizon** [comment]
OK yeah I think I know whats happening then. The PHP config isn't being used.
Can you tell me whats in the /etc/php folder?
I bet its a 7.0 and a 7.3 folder right?
Thanks for helping with this by the way...

**Comment by JVTEAM** [comment]
Thanks for your help.  Yes, there is a 7.0 and 7.3 folder.

**Comment by NeonHorizon** [comment]
Can you please run the following commands to copy the PHP7.0 config to PHP7.3, then reboot and try again?
sudo cp /etc/php/7.0/apache2/conf.d/berryio.ini /etc/php/7.3/apache2/conf.d/berryio.ini
sudo cp /etc/php/7.0/apache2/conf.d/msmtp.ini /etc/php/7.3/apache2/conf.d/msmtp.ini
sudo cp /etc/php/7.0/cli/conf.d/berryio.ini /etc/php/7.3/cli/conf.d/berryio.ini
sudo cp /etc/php/7.0/cli/conf.d/msmtp.ini /etc/php/7.3/cli/conf.d/msmtp.ini

Thanks....

**Comment by JVTEAM** [comment]
That did it!  Thanks!

**Comment by NeonHorizon** [comment]
Great I will modify BerryIO!

**Comment by NeonHorizon** [comment]
I've just added a new version, hopefully it works as I've not had time to test.
