### ISSUE TITLE
Trying to crete a new tile to execute a shell command

### ISSUE THREAD

**Issue by f00j00** [NeonHorizon/berryio#33]
Hello,

I'm using BerryIO + the nicholas smartapp

I was able to duplicate the reboot tile which launches api_command/reboot

I replced it with another command api_commnd/sudo ps4-waker

But its not working...

Can you please help point out what should I do?>

**Comment by NeonHorizon** [comment]
You cannot use api_command to run any command, only the BerryIO API commands listed here:
https://github.com/NeonHorizon/berryio/blob/master/includes/configs/api.php

**Comment by f00j00** [comment]
Hi,

Is there anyway I can add more commands?

I already added the ps4-waker command to that list...but it needs sudo and still doesn't work..

Need your help please.

**Comment by NeonHorizon** [comment]
Yes but its not easy....

Add the name in this list:
https://github.com/NeonHorizon/berryio/blob/master/includes/configs/api.php

To use sudo please add the command to NEED_SUDO here but it might not work through the web interface:
https://github.com/NeonHorizon/berryio/blob/master/includes/configs/common.php

Add the php script in this folder (this is the hard bit you will probably need the exec command):
https://github.com/NeonHorizon/berryio/tree/master/includes/commands

**Comment by f00j00** [comment]
This is exactly what I did.

Add the name in this list:
https://github.com/NeonHorizon/berryio/blob/master/includes/configs/api.php (DONE - added "ps4-waker"):

pi@raspberrypi:/usr/share/berryio/includes/configs $ cat api.php 
<?
/*------------------------------------------------------------------------------
  BerryIO API Compatable Commands
------------------------------------------------------------------------------*/

$GLOBALS['API_COMMANDS'] = array(
  'gpio_status',
  'gpio_set_mode',
  'gpio_set_value',
  'camera_status',
  'camera_take_image',
  'camera_show',
  'camera_delete',
  'spi_status',
  'spi_set_dac_value',
  'lcd_initialise',
  'lcd_output',
  'lcd_position',
  'lcd_command',
  'cpu_status',
  'memory_status',
  'disk_status',
  'reboot',
  'shutdown',
  'version',
  'smartthings',
  'ps4-waker',
);
pi@raspberrypi:/usr/share/berryio/includes/configs $ 



To use sudo please add the command to NEED_SUDO here but it might not work through the web interface:
https://github.com/NeonHorizon/berryio/blob/master/includes/configs/common.php (DONE:)

pi@raspberrypi:/usr/share/berryio/includes/configs $ cat common.php 
<?
/*------------------------------------------------------------------------------
  BerryIO Common Configuration
------------------------------------------------------------------------------*/

// Real name of application
define('REAL_NAME', 'BerryIO');

// Commands which need sudo
$GLOBALS['NEED_SUDO'] = array('board_status', 'smartthings', 'cpu_status', 'memory_status', 'camera_setup', 'system_status', 'network_status', 'email_ip', 'upgrade', 'reboot', 'shutdown', 'lcd_initialise', 'lcd_position', 'lcd_command', 'lcd_output', 'gpio_status', 'gpio_get_values', 'gpio_set_mode', 'gpio_set_value', 'spi_status', 'spi_get_values', 'spi_set_dac_value', 'ps4-waker');

// Storage for javascripts which need displaying/executing
$GLOBALS['JAVASCRIPT_RUN'] = array();
$GLOBALS['JAVASCRIPT'] = array();




Add the php script in this folder (this is the hard bit you will probably need the exec command):
https://github.com/NeonHorizon/berryio/tree/master/includes/commands (DONE: I copied reboot.php to ps4-waker.php and modified it as follows:)
pi@raspberrypi:/usr/share/berryio/includes/commands $ cat ps4-waker.php 
<?
/*------------------------------------------------------------------------------
  BerryIO Reboot Command
------------------------------------------------------------------------------*/

$title = 'Power Control';

// Load the power functions
require_once(FUNCTIONS.'power.php');

// Reboot
if($GLOBALS['EXEC_MODE'] == 'html' && isset($_POST['no']))
  go_to('welcome');
elseif($GLOBALS['EXEC_MODE'] == 'html' && !isset($_POST['yes']))
  $content .= view('are_you_sure', array('description' => 'pse4-waker'));
elseif(power_reboot() === FALSE)
{
  $content .= message('ERROR: Cannot reboot the system', 'welcome');
  return FALSE;
}
elseif($GLOBALS['EXEC_MODE'] != 'api')
  $content .= message('See you again shortly!', 'welcome');
pi@raspberrypi:/usr/share/berryio/includes/commands $ 


in the ST Device Handler (nicholaswilde : Raspberry Pi), Here is what I added:


 command "restart"
        command "reboot"
        command "PS4ON"
        command "PS4OFF"


**standardTile("PS4ON", "device.PS4ON", inactiveLabel: false, decoration: "flat") {
        	state "default", action:"PS4ON", label: "PS4ON", displayName: "PS4ON"
        }
         standardTile("PS4OFF", "device.PS4OFF", inactiveLabel: false, decoration: "flat") {
        	state "default", action:"PS4OFF", label: "PS4OFF", displayName: "PS4OFF"


def PS4ON(){
	log.debug "PS4 ON"
    sendEvent(name: "switch", value: "off")
    def uri = "ps4-waker"
    postAction(uri)
}
def PS4OFF(){
	log.debug "PS4 OFF"
    sendEvent(name: "switch", value: "off")
    def uri = "/api_commnd/ps4-waker standby"
    postAction(uri)
}

**Comment by f00j00** [comment]
> 
pi@raspberrypi:/usr/share/berryio/includes/configs $ cat common.php 
<?
/*------------------------------------------------------------------------------
  BerryIO Common Configuration
------------------------------------------------------------------------------*/

// Real name of application
define('REAL_NAME', 'BerryIO');

// Commands which need sudo
$GLOBALS['NEED_SUDO'] = array('board_status', 'smartthings', 'cpu_status', 'memory_status', 'camera_setup', 'system_status', 'network_status', 'email_ip', 'upgrade', 'reboot', 'shutdown', 'lcd_initialise', 'lcd_position', 'lcd_command', 'lcd_output', 'gpio_status', 'gpio_get_values', 'gpio_set_mode', 'gpio_set_value', 'spi_status', 'spi_get_values', 'spi_set_dac_value', 'ps4-waker');

// Storage for javascripts which need displaying/executing
$GLOBALS['JAVASCRIPT_RUN'] = array();
$GLOBALS['JAVASCRIPT'] = array();




pi@raspberrypi:/usr/share/berryio/includes/configs $ cat api.php 
<?
/*------------------------------------------------------------------------------
  BerryIO API Compatable Commands
------------------------------------------------------------------------------*/

$GLOBALS['API_COMMANDS'] = array(
  'gpio_status',
  'gpio_set_mode',
  'gpio_set_value',
  'camera_status',
  'camera_take_image',
  'camera_show',
  'camera_delete',
  'spi_status',
  'spi_set_dac_value',
  'lcd_initialise',
 'lcd_output',
  'lcd_position',
  'lcd_command',
  'cpu_status',
  'memory_status',
  'disk_status',
  'reboot',
  'shutdown',
  'version',
  'smartthings',
  'ps4-waker',
);

**Comment by f00j00** [comment]
hmmm

im not sure why the format is that bad,

`pi@raspberrypi:/usr/share/berryio/includes/configs $ cat common.php 
<?
/*------------------------------------------------------------------------------
  BerryIO Common Configuration
------------------------------------------------------------------------------*/

// Real name of application
define('REAL_NAME', 'BerryIO');

// Commands which need sudo
$GLOBALS['NEED_SUDO'] = array('board_status', 'smartthings', 'cpu_status', 'memory_status', 'camera_setup', 'system_status', 'network_status', 'email_ip', 'upgrade', 'reboot', 'shutdown', 'lcd_initialise', 'lcd_position', 'lcd_command', 'lcd_output', 'gpio_status', 'gpio_get_values', 'gpio_set_mode', 'gpio_set_value', 'spi_status', 'spi_get_values', 'spi_set_dac_value', 'ps4-waker');

// Storage for javascripts which need displaying/executing
$GLOBALS['JAVASCRIPT_RUN'] = array();
$GLOBALS['JAVASCRIPT'] = array();
pi@raspberrypi:/usr/share/berryio/includes/configs $ cat api.php 
<?
/*------------------------------------------------------------------------------
  BerryIO API Compatable Commands
------------------------------------------------------------------------------*/

$GLOBALS['API_COMMANDS'] = array(
  'gpio_status',
  'gpio_set_mode',
  'gpio_set_value',
  'camera_status',
  'camera_take_image',
  'camera_show',
  'camera_delete',
  'spi_status',
  'spi_set_dac_value',
  'lcd_initialise',
  'lcd_output',
  'lcd_position',
  'lcd_command',
  'cpu_status',
  'memory_status',
  'disk_status',
'reboot',
  'shutdown',
  'version',
  'smartthings',
  'ps4-waker',
);
pi@raspberrypi:/usr/share/berryio/includes/configs $ cd ..
pi@raspberrypi:/usr/share/berryio/includes $ cd commands/
pi@raspberrypi:/usr/share/berryio/includes/commands $ cat ps4
ps4off.php     ps4on.php      ps4-waker.php  
pi@raspberrypi:/usr/share/berryio/includes/commands $ cat ps4
ps4off.php     ps4on.php      ps4-waker.php  
pi@raspberrypi:/usr/share/berryio/includes/commands $ cat ps4-waker.php 
<?
/*------------------------------------------------------------------------------
  BerryIO Reboot Command
------------------------------------------------------------------------------*/

$title = 'Power Control';

// Load the power functions
require_once(FUNCTIONS.'power.php');

// Reboot
if($GLOBALS['EXEC_MODE'] == 'html' && isset($_POST['no']))
  go_to('welcome');
go_to('welcome');
elseif($GLOBALS['EXEC_MODE'] == 'html' && !isset($_POST['yes']))
  $content .= view('are_you_sure', array('description' => 'pse4-waker'));
elseif(power_reboot() === FALSE)
{
  $content .= message('ERROR: Cannot reboot the system', 'welcome');
  return FALSE;
}
elseif($GLOBALS['EXEC_MODE'] != 'api')
  $content .= message('See you again shortly!', 'welcome');


`

**Comment by f00j00** [comment]
`def PS4ON(){
	log.debug "PS4 ON"
    sendEvent(name: "switch", value: "off")
    def uri = "ps4-waker"
    postAction(uri)
}
def PS4OFF(){
	log.debug "PS4 OFF"
    sendEvent(name: "switch", value: "off")
    def uri = "/api_commnd/ps4-waker standby"
    postAction(uri)
}`

**Comment by NeonHorizon** [comment]
I can't read this because of the formatting. When you paste it in click the <> insert code button.
Also what language is that, it doesn't look like PHP?

**Comment by f00j00** [comment]
Add the name in this list:
https://github.com/NeonHorizon/berryio/blob/master/includes/configs/api.php 

Done:

`pi@raspberrypi:/usr/share/berryio/includes/configs $ cat api.php 
<?
/*------------------------------------------------------------------------------
  BerryIO API Compatable Commands
------------------------------------------------------------------------------*/

$GLOBALS['API_COMMANDS'] = array(
  'gpio_status',
  'gpio_set_mode',
  'gpio_set_value',
  'camera_status',
  'camera_take_image',
  'camera_show',
  'camera_delete',
  'spi_status',
  'spi_set_dac_value',
  'lcd_initialise',
  'lcd_output',
  'lcd_position',
  'lcd_command',
  'cpu_status',
  'memory_status',
  'disk_status',
  'reboot',
  'shutdown',
  'version',
  'smartthings',
  'ps4-waker',
);`

**Comment by f00j00** [comment]
What the hell, i paste the whole text in between `` and its not pasting all the text..

Is there any other way to better reach you? or are you seeing all what i'm pasting in the code?

**Comment by f00j00** [comment]
I'm pasting to you what I did in all 3 points you mentioned.

**Comment by f00j00** [comment]
I copied reboot.php to ps4-waker.php as follows:

`pi@raspberrypi:/usr/share/berryio/includes/commands $ cat ps4-waker.php 
<?
/*------------------------------------------------------------------------------
  BerryIO Reboot Command
------------------------------------------------------------------------------*/

$title = 'Power Control';

// Load the power functions
require_once(FUNCTIONS.'power.php');

// Reboot
if($GLOBALS['EXEC_MODE'] == 'html' && isset($_POST['no']))
  go_to('welcome');
elseif($GLOBALS['EXEC_MODE'] == 'html' && !isset($_POST['yes']))
  $content .= view('are_you_sure', array('description' => 'ps4-waker'));
elseif(power_reboot() === FALSE)
{
  $content .= message('ERROR: Cannot reboot the system', 'welcome');
  return FALSE;
}
elseif($GLOBALS['EXEC_MODE'] != 'api')
  $content .= message('See you again shortly!', 'welcome');
pi@raspberrypi:/usr/share/ber`

**Comment by f00j00** [comment]
In ST Device Handler, I added these:

`command "restart"
        command "reboot"
        command "PS4ON"
        command "PS4OFF"`



`      details(["button", "temperature", "cpuPercentage", "memory" , "diskUsage", "contact", "restart", "refresh", "reboot", "PS4ON", "PS4OFF"])`



`def PS4ON(){
	log.debug "PS4 ON"
    sendEvent(name: "switch", value: "off")
    def uri = "ps4-waker"
    postAction(uri)
}
def PS4OFF(){
	log.debug "PS4 OFF"
    sendEvent(name: "switch", value: "off")
    def uri = "/api_commnd/ps4-waker standby"
    postAction(uri)
}`

**Comment by f00j00** [comment]
Can you read it now?

**Comment by NeonHorizon** [comment]
I think this is going to be too complicated to support in a github issue but I think you have multiple problems. For example you have told the system the API commands are PS4ON and PS4OFF but you only have one file called ps4-waker.php in commands. It needs to match, so you need two files one called PS4ON.php and one called PS4OFF.php and they each need to do whatever it is you need the command to do.

**Comment by f00j00** [comment]
do you have an email? or google chat?

**Comment by f00j00** [comment]
> I think this is going to be too complicated to support in a github issue but I think you have multiple problems. For example you have told the system the API commands are PS4ON and PS4OFF but you only have one file called ps4-waker.php in commands. It needs to match, so you need two files one called PS4ON.php and one called PS4OFF.php and they each need to do whatever it is you need the command to do.

but the command itself is ps4-waker not PS4ON <- this was just a name/alas but at the command itself which i believe is /api_commands/ps4-waker

**Comment by f00j00** [comment]
All i wanna do is duplicate the reboot command with another one with a new tile:
i did the tile
i tried to duplicate all files and edited .groove file
but it just wont work when i press PS4ON
reboot works..

**Comment by NeonHorizon** [comment]
Have you tried it on the command line, its best to get it to work there first.
berryio api_command ps4-waker

**Comment by f00j00** [comment]
> Have you tried it on the command line, its best to get it to work there first.
> berryio api_command ps4-waker

pi@raspberrypi:/usr/share/berryio/includes/commands $ berryio api_command ps4-waker
ERROR: Unknown Command

**Comment by NeonHorizon** [comment]
The only way I can think of that you would get that error is if ps4-waker isn't in this file?
https://github.com/NeonHorizon/berryio/blob/master/includes/configs/api.php
