### ISSUE TITLE
Not working with new Raspbian and PHP 7.4 w/fix

### ISSUE THREAD

**Issue by gitothy** [NeonHorizon/berryio#35]
Just to note that BerryIO isn't working with the new PHP 7.4.  Per the fix noted for 7.3, you must now run the below and restart the Pi.

`sudo cp /etc/php/7.0/apache2/conf.d/berryio.ini /etc/php/7.4/apache2/conf.d/berryio.ini`

`sudo cp /etc/php/7.0/apache2/conf.d/msmtp.ini /etc/php/7.4/apache2/conf.d/msmtp.ini`

`sudo cp /etc/php/7.0/cli/conf.d/berryio.ini /etc/php/7.4/cli/conf.d/berryio.ini`

`sudo cp /etc/php/7.0/cli/conf.d/msmtp.ini /etc/php/7.4/cli/conf.d/msmtp.ini`

**Comment by NeonHorizon** [comment]
That doesn't surprise me. I'm not really maintaining this actively any more but if the config files fix the problem it I'm happy to duplicate the config files in default_config/php/7.3 to default_config/php/7.4 which should solve it during installation I would guess.
